# Generated by Django 4.2.5 on 2023-10-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpeliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=20)),
                ('nombrelibro', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='clientes',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
