# Generated by Django 4.2.5 on 2023-10-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpeliculas', '0003_alter_clientes_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='libros',
            name='nombrelibro',
            field=models.CharField(max_length=100),
        ),
    ]
